# Generated by Django 5.2.5 on 2025-10-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_table',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
