# Generated by Django 5.2.5 on 2025-10-27 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_table_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='malpratice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malpratice', models.CharField(max_length=50)),
                ('EXAM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.exam_table')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student_table')),
            ],
        ),
    ]
