# Generated by Django 5.2.5 on 2025-10-27 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_malpratice'),
    ]

    operations = [
        migrations.AddField(
            model_name='malpratice',
            name='QUESTION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.question_table'),
            preserve_default=False,
        ),
    ]
