# Generated by Django 5.2.5 on 2025-10-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_malpratice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='malpratice',
            name='date',
            field=models.DateField(default='2025-10-27'),
            preserve_default=False,
        ),
    ]
